### ISSUE TITLE
determine which HA connection has returned AddEventHandlerSubscriptionAsync event

### ISSUE THREAD

**Issue by pcgear** [vicfergar/HassClient#14]
I am trying to connect multiple Home Assistant controllers to my code.  The code snippet below is working and I am getting responses from two controllers.  The problem is I can't determine which controller returns the response.  I realize I could add different WS_OnEvent functions to separate the returns but that becomes cumbersome if there are 50 connections.  Is there some method to make this determination more cleanly?

           var hassWSApi = new HassWSApi();
            var connectionParameters = ConnectionParameters.CreateFromInstanceBaseUrl("http://192.168.55.125:8123/", "...");
            await hassWSApi.ConnectAsync(connectionParameters);

            var hassWSApi2 = new HassWSApi();
            connectionParameters = ConnectionParameters.CreateFromInstanceBaseUrl("http://192.168.55.165:8123/", "...");
            await hassWSApi2.ConnectAsync(connectionParameters);

            await hassWSApi.AddEventHandlerSubscriptionAsync(WS_OnEvent);
            await hassWSApi2.AddEventHandlerSubscriptionAsync(WS_OnEvent);

**Comment by vicfergar** [comment]
Thank you for reporting this issue. I apologize for the delayed response.

I'm happy to inform you that I've implemented a change that addresses your concern about identifying which instance returns the response. The event sender is now the `HassClientWebSocket` instance instead of an internal subscription object.

You can now identify the source connection in your event handlers like this:
```C#
private void WS_OnEvent(object sender, EventResultInfo e)
{
    if (sender == hassWSApi.WebSocker) 
    {
        Console.WriteLine($"Event from connection: {webSocket.ConnectionState}");
    }
}
```
